/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LNV
 */
public class FormPEPN extends javax.swing.JFrame {

    /**
     * Creates new form FormPEPN
     */
    public FormPEPN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTempo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Clientes = new javax.swing.JTable();
        txtCPF = new javax.swing.JFormattedTextField();
        txtTel = new javax.swing.JFormattedTextField();
        txtCapital = new javax.swing.JTextField();
        bnt_Salvar = new javax.swing.JButton();
        bnt_Salvar1 = new javax.swing.JButton();
        bnt_Deletar = new javax.swing.JButton();
        btn_Atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro PEPN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nome");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Capital");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("CPF");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 131, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Endereço");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Tel");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 187, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Tempo a pagar (por mês)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 145, -1));
        jPanel1.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 163, -1));
        jPanel1.add(txtTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 163, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 170));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tb_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Juros", "Endereço", "Tempo a Pagar", "Capital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ClientesMouseClicked(evt);
            }
        });
        tb_Clientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_ClientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Clientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 570, 130));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 156, 145, -1));

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 212, 145, -1));
        jPanel1.add(txtCapital, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 163, -1));

        bnt_Salvar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bnt_Salvar.setText("Salvar");
        bnt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_SalvarActionPerformed(evt);
            }
        });
        jPanel1.add(bnt_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        bnt_Salvar1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bnt_Salvar1.setText("Limpar");
        bnt_Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_Salvar1ActionPerformed(evt);
            }
        });
        jPanel1.add(bnt_Salvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        bnt_Deletar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bnt_Deletar.setText("Deletar");
        bnt_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_DeletarActionPerformed(evt);
            }
        });
        jPanel1.add(bnt_Deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        btn_Atualizar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/P.E.P.N agiotagens.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ClientesMouseClicked
        // Mostrar dados da tabela com o mause:

    mostrarDados();

    }//GEN-LAST:event_tb_ClientesMouseClicked

    private void tb_ClientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_ClientesKeyReleased
        // Mostrar dados da tabela com o teclado:

    mostrarDados();

    }//GEN-LAST:event_tb_ClientesKeyReleased

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void bnt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_SalvarActionPerformed
        // Codigo do botão Salvar:

        salvar();
    }//GEN-LAST:event_bnt_SalvarActionPerformed

    private void bnt_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_Salvar1ActionPerformed
        // Limpar os dados sem ser o da abela:

        limparDados();
    }//GEN-LAST:event_bnt_Salvar1ActionPerformed

    private void bnt_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_DeletarActionPerformed
        // Codigo para deletar dados da tebela:

        //tb_Clientes.getSelectedRow();

        deletar();
    }//GEN-LAST:event_bnt_DeletarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        
        atualizar ();
        
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPEPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPEPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPEPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPEPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPEPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_Deletar;
    private javax.swing.JButton bnt_Salvar;
    private javax.swing.JButton bnt_Salvar1;
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_Clientes;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTel;
    private javax.swing.JTextField txtTempo;
    // End of variables declaration//GEN-END:variables


    private void atualizar (){

        if(tb_Clientes.getSelectedRow() != -1){
            
            Double valor = Double.parseDouble(txtCapital.getText()) * 0.08 * 
            Double.parseDouble(txtTempo.getText()) + 
            Double.parseDouble(txtCapital.getText());

            tb_Clientes.setValueAt(txtNome.getText(), tb_Clientes.getSelectedRow(), 0);
            tb_Clientes.setValueAt(txtCPF.getText(), tb_Clientes.getSelectedRow(), 1);
            tb_Clientes.setValueAt(txtTel.getText(), tb_Clientes.getSelectedRow(), 2);
            tb_Clientes.setValueAt(txtTempo.getText(), tb_Clientes.getSelectedRow(), 5);
            tb_Clientes.setValueAt(txtEndereco.getText(), tb_Clientes.getSelectedRow(), 4);
            tb_Clientes.setValueAt(valor, tb_Clientes.getSelectedRow(), 3);
            tb_Clientes.setValueAt(txtCapital.getText(), tb_Clientes.getSelectedRow(), 6);

        }

    }

    private void salvar (){

    DefaultTableModel dtmCadastros = (DefaultTableModel) tb_Clientes.getModel();  
    
    // Capital * 0.08 * t
    Double valor = Double.parseDouble(txtCapital.getText()) * 0.08 * 
            Double.parseDouble(txtTempo.getText()) + 
            Double.parseDouble(txtCapital.getText());
    
    Object[] dados = {txtNome.getText(), txtCPF.getText(), txtTel.getText(), 
        valor, txtEndereco.getText(), txtTempo.getText(), txtCapital.getText()};

    
    dtmCadastros.addRow(dados);

    limparDados();

    }

    private void deletar (){

        if(tb_Clientes.getSelectedRow() != -1){ 

        DefaultTableModel dtmCadastros = (DefaultTableModel) tb_Clientes.getModel();

        dtmCadastros.removeRow(tb_Clientes.getSelectedRow());

        limparDados();

        }
            else{

                JOptionPane.showMessageDialog(null, "Selecione um cadastro para deletar!!!");

            }

    }

    private void limparDados (){
     
        txtNome.setText("");
        txtTempo.setText("");
        txtCPF.setText("");
        txtEndereco.setText("");
        txtTel.setText("");
        txtCapital.setText("");

    }

    private void mostrarDados (){

    if(tb_Clientes.getSelectedRow() != -1){

        txtNome.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 0).toString());
        txtCPF.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 1).toString());
        txtTel.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 2).toString());
        txtCapital.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 6).toString());
        txtEndereco.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 4).toString());
        txtTempo.setText(tb_Clientes.getValueAt(tb_Clientes.getSelectedRow(), 5).toString());
  
      }

    }

}
